# Generated by Django 3.1.2 on 2020-10-15 19:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=documents.models.rename_document_pdf,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
                verbose_name="PDF file",
            ),
        ),
        migrations.CreateModel(
            name="PrintJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report",
                    models.CharField(
                        choices=[
                            ("barcode_label", "Barcode label"),
                            ("info_paper", "Information paper with barcode"),
                        ],
                        max_length=255,
                        verbose_name="Report to print",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="print_jobs",
                        to="documents.document",
                        verbose_name="Document to print",
                    ),
                ),
            ],
            options={"verbose_name": "Print job", "verbose_name_plural": "Print jobs",},
        ),
    ]
