# Generated by Django 3.1.2 on 2020-10-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_print_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="printjob",
            name="is_printed",
            field=models.BooleanField(default=False, verbose_name="Printed"),
        ),
        migrations.AddField(
            model_name="printjob",
            name="printed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Printed at"
            ),
        ),
    ]
