name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: hansegucker/documento
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: hansegucker/documento
#      - name: Publish to Registry 2
#        uses: elgohr/Publish-Docker-Github-Action@master
#        with:
#          name: hansegucker/documento/documento
#          username: ${{ secrets.GITHUB_USERNAME }}
#          password: ${{ secrets.GITHUB_PASSWORD }}
#          registry: docker.pkg.github.com
#      - name: Slack notification
#        env:
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#        uses: Ilshidur/action-slack@master
#        with:
#          args: 'A new image has been build.'
