name: Reformat

on: push

jobs:
  reformat:
    name: Reformat code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Black
        uses: lgeiger/black-action@master
        args: "."

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Required
          commit_message: Reformat source code

          commit_options: '--no-verify --signoff'

          file_pattern: *.py

          # Optional commit user and author settings
        #    commit_user_name: My GitHub Actions Bot
        #   commit_user_email: my-github-actions-bot@example.org
        #  commit_author: Author <actions@github.com>


