name: Reformat

on:
  pull_request:
  push:

jobs:
  prettier:
    name: Run prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v2.2
        with:
          commit_message: "Prettify code using prettier"
          prettier_options: --write frontend/**/*.{js,jsx,html,css,json,ts,tsx}

  black:
    name: Run black
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run Black
        uses: lgeiger/black-action@master
        with:
          args: "."

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Required
          commit_message: "Reformat code using black"

          commit_options: '--no-verify --signoff'

          file_pattern: "*.py"

          # Optional commit user and author settings
        #    commit_user_name: My GitHub Actions Bot
        #   commit_user_email: my-github-actions-bot@example.org
        #  commit_author: Author <actions@github.com>


